home/urls.py
"""Defines URL patterns for home."""

from django.urls import path

from . import views

app_name = "home"
urlpatterns = [
    # Home page.
    path("", views.index, name="index"),
    # Page that shows privacy info.
    path(
        "privacy/",
        views.privacy,
        name="privacy",
    ),
    # Page that shows terms info.
    path(
        "terms/",
        views.terms,
        name="terms",
    ),
    # Page that shows contact info and form.
    path(
        "contact/",
        views.contact,
        name="contact",
    ),
    # Page that shows contact form success message.
    path(
        "contact/sent/",
        views.contact_sent,
        name="contact_sent",
    ),
    # Page that shows options relating to account for logged in users.
    path("my-account/", views.my_account, name="my_account"),
    # Page that shows pricing info.
    path("pricing/", views.pricing, name="pricing"),
]

teachmestem/urls.py
from allauth.account.decorators import secure_admin_login
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

admin.autodiscover()
admin.site.login = secure_admin_login(admin.site.login)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("home.urls")),
    path("tutoring/", include("tutoring.urls")),
    path("courses/", include("courses.urls")),
    path("revise/", include("revision.urls")),
]

if settings.DEBUG:
    from debug_toolbar.toolbar import debug_toolbar_urls

    urlpatterns += debug_toolbar_urls()

tutoring/urls.py
"""Defines URL patterns for tutoring."""

from django.urls import path

from . import views

app_name = "tutoring"

urlpatterns = [
    # Page that shows tutoring info.
    path(
        "",
        views.tutoring,
        name="tutoring",
    ),
    # Page that shows tutoring contact info.
    path(
        "<int:tutor_id>/contact/",
        views.tutoring_contact,
        name="tutoring_contact",
    ),
    # Page that shows tutoring contact form success message.
    path(
        "<int:tutor_id>/contact/sent/",
        views.tutoring_contact_sent,
        name="tutoring_contact_sent",
    ),
]

tutoring/models.py
from django.contrib.auth.models import User
from django.db import models


class Tutor(models.Model):
    """A user who is a tutor."""

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    text = models.TextField()
    is_available = models.BooleanField(default=True)

    def __str__(self):
        """Return a string representation of the model."""
        return f"{self.name}"


class TutoringContactUser(models.Model):
    """A user who contacts via the Tutoring Contact Form."""

    tutor = models.ForeignKey(Tutor, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        """Return a string representation of the model."""
        return f"{self.first_name} {self.last_name}"

tutoring/forms.py
from django import forms
from django_recaptcha.fields import ReCaptchaField
from django_recaptcha.widgets import ReCaptchaV3

from .models import TutoringContactUser


class TutoringContactForm(forms.ModelForm):
    captcha = ReCaptchaField(widget=ReCaptchaV3)

    class Meta:
        model = TutoringContactUser
        fields = ["tutor", "first_name", "last_name", "email", "message"]
        labels = {
            "tutor": "Tutor",
            "email": "Email address",
            "message": "Message",
        }
        widgets = {"message": forms.Textarea(attrs={"style": "height:150px"})}

tutoring/views.py
from django.core.mail import send_mail
from django.shortcuts import redirect, render


from .forms import TutoringContactForm
from .models import Tutor


def tutoring(request):
    """Show tutoring page."""
    tutors = Tutor.objects.all()
    context = {
        "tutors": tutors,
    }
    return render(request, "tutoring/tutoring.html", context)


def tutoring_contact(request, tutor_id):
    """Show tutoring contact page."""
    tutor = Tutor.objects.get(id=tutor_id)
    if request.method != "POST":
        form = TutoringContactForm()
    else:
        form = TutoringContactForm(data=request.POST)
        if form.is_valid():
            send_mail(
                subject=f"{form.cleaned_data['first_name']} {form.cleaned_data['last_name']} has requested tutoring!",
                message=f"""Requested tutor: {tutor.name}
                    Name: {form.cleaned_data["first_name"]} {form.cleaned_data["last_name"]} 
                    Email: {form.cleaned_data["email"]}
                    Message:
                    
                    {form.cleaned_data["message"]}
                    
                    """,
                from_email=None,
                recipient_list=[],
            )
            form.save()
            return redirect("tutoring:tutoring_contact_sent", tutor_id)

    context = {
        "tutor": tutor,
        "form": form,
    }
    return render(request, "tutoring/tutoring_contact.html", context)


def tutoring_contact_sent(request, tutor_id):
    """Show tutoring contact form success page."""
    return render(request, "tutoring/tutoring_contact_sent.html")

tutoring/templates/tutoring/tutoring.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}
    Tutoring ·
{% endblock title %}
{% block breadcrumb %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a 
                    href="{% url 'home:index' %}"
                    class="text-info link-secondary link-underline-opacity-0">
                    Home
                </a>
            </li>
            <li class="breadcrumb-item" aria-current="page">Tutoring</li>
        </ol>
    </nav>
{% endblock breadcrumb %}
{% block page_header %}
    <h1 class="border-none pb-2 my-3 d-flex justify-content-center display-5 fw-bold text-body-emphasis">Tutoring</h1>
{% endblock page_header %}
{% block content_1 %}
    <div class="container">
        <div class="row row-cols-1 row-cols-md-2 mb-3 text-center g-4">
            {% for tutor in tutors %}
                <div class="col">
                    <div class="card mb-4 rounded-3 shadow-lg h-100">
                        <div class="text-info card-header py-3 border-0">
                            <img
                                class="card-img-top"
                                alt="tutor icon"
                                src="{% static 'images/man.svg' %}"
                                width="80"
                                height="80">
                            <h3 class="my-0 fw-bold pt-3">{{ tutor.name }}</h3>
                        </div>
                        <div class="card-body mt-3">
                            {{ tutor.text|linebreaksbr }}
                            <div>
                                {% if tutor.is_available %}
                                    <a href="{% url 'tutoring:tutoring_contact' tutor.id %}" class="btn btn-primary-landing rounded-pill border-0 mt-5">Get in touch!</a>
                                {% else %}
                                    <button class="btn btn-primary-landing rounded-pill border-0 mt-5" disabled>All slots are booked</button>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock content_1 %}

tutoring/templates/tutoring/tutoring_contact.html
{% extends 'home/base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block title %}
    Tutoring Contact ·
{% endblock title %}
{% block breadcrumb %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a 
                    href="{% url 'home:index' %}"
                    class="text-info link-secondary link-underline-opacity-0">
                    Home
                </a>
            </li>
            <li class="breadcrumb-item">
                <a 
                    href="{% url 'tutoring:tutoring' %}"
                    class="text-info link-secondary link-underline-opacity-0">
                    Tutoring
                </a>
            </li>
            <li class="breadcrumb-item" aria-current="page">Contact</li>
        </ol>
    </nav>
{% endblock breadcrumb %}
{% block page_header %}
    <h1 class="border-none pb-2 my-3 d-flex justify-content-center display-5 fw-bold text-body-emphasis">Tutoring Contact</h1>
{% endblock page_header %}
{% block content_1 %}
    <div class="container">
        <p class="d-flex justify-content-center mb-2">Please fill in the details below to get in touch.</p>
        <div class="card-header py-3 border-0 mt-5">
            <h5 class="d-flex justify-content-center fw-semibold mb-4">Tutor</h5>
            <img
                class="card-img-top"
                alt="tutor icon"
                src="{% static 'images/man.svg' %}"
                width="80"
                height="80">
            <h3 class="text-info d-flex justify-content-center fw-bold pt-3 mb-3">{{ tutor.name }}</h3>
        </div>
        <div class="d-flex justify-content-center">
            <form action="{% url 'tutoring:tutoring_contact' tutor.id %}" method='post'>
                {% csrf_token %}
                <input type="hidden" name="tutor" maxlength="200" class="form-control" required id="id_tutor" value="{{ tutor.id }}">
                {% bootstrap_form form exclude="tutor" layout="floating" %}
                <div class="d-flex justify-content-center">
                    <button class="btn btn-primary-tms rounded-pill px-4 py-2 border-0" type="submit">Send</button>
                </div>
            </form>
        </div>
    </div>
{% endblock content_1 %}

tutoring/templates/tutoring/tutoring_contact_sent.html
{% extends 'tutoring/tutoring_contact.html' %}
{% block content_1 %}
    <div class="container">
        <h2 class="mt-5 py-3 d-flex justify-content-center">
            Sent!
        </h2>
        <h2 class="mt-5 py-3 d-flex justify-content-center">
            We'll get back to you as soon as possible.
        </h2>
    </div>
{% endblock content_1 %}