courses/urls.py
"""Defines URL patterns for courses."""

from django.urls import path

from . import views

app_name = "courses"

urlpatterns = [
    # Page that shows courses info.
    path(
        "",
        views.courses,
        name="courses",
    ),
    # Page that shows course registration info and form.
    path(
        "<int:course_id>/register/",
        views.courses_register,
        name="courses_register",
    ),
    # Page that shows course registration form success message.
    path(
        "<int:course_id>/register/success/",
        views.courses_register_success,
        name="courses_register_success",
    ),
]

home/urls.py
"""Defines URL patterns for home."""

from django.urls import path

from . import views

app_name = "home"
urlpatterns = [
    # Home page.
    path("", views.index, name="index"),
    # Page that shows privacy info.
    path(
        "privacy/",
        views.privacy,
        name="privacy",
    ),
    # Page that shows terms info.
    path(
        "terms/",
        views.terms,
        name="terms",
    ),
    # Page that shows contact info and form.
    path(
        "contact/",
        views.contact,
        name="contact",
    ),
    # Page that shows contact form success message.
    path(
        "contact/sent/",
        views.contact_sent,
        name="contact_sent",
    ),
    # Page that shows options relating to account for logged in users.
    path("my-account/", views.my_account, name="my_account"),
    # Page that shows pricing info.
    path("pricing/", views.pricing, name="pricing"),
]

revision/urls.py
"""Defines URL patterns for revision."""

from django.urls import path

from . import views

app_name = "revision"
urlpatterns = [
    # Page that shows 'My Subjects' for logged in users.
    path(
        "my-subjects/",
        views.my_subjects,
        name="my_subjects",
    ),
    # Page that shows subjects for a given qualification.
    path(
        "<slug:qualification_slug>/",
        views.qualification,
        name="qualification",
    ),
    # Page that show exam boards for a given subject.
    path(
        "<slug:qualification_slug>/<int:subject_id>/<slug:subject_slug>/",
        views.subject,
        name="subject",
    ),
    # Page that shows links to revision notes, questions, and past papers for a given exam board.
    path(
        "<slug:qualification_slug>/<slug:subject_slug>/<int:examboard_id>/<slug:examboard_slug>/",
        views.examboard,
        name="examboard",
    ),
    # Page that shows notes belonging to a topic.
    path(
        "<slug:qualification_slug>/<slug:subject_slug>/<slug:examboard_slug>/<int:topic_id>/<slug:topic_slug>/notes/",
        views.notes,
        name="notes",
    ),
    # Page that shows questions belonging to a topic.
    path(
        "<slug:qualification_slug>/<slug:subject_slug>/<slug:examboard_slug>/<int:topic_id>/<slug:topic_slug>/questions/",
        views.questions,
        name="questions",
    ),
    # Page that shows a past paper belonging to an exam board.
    path(
        "<slug:qualification_slug>/<slug:subject_slug>/<slug:examboard_slug>/<int:pastpaper_id>/<str:pastpaper_name>/past-paper/",
        views.past_paper,
        name="past_paper",
    ),
    # Page that shows a past paper's model answers.
    path(
        "<slug:qualification_slug>/<slug:subject_slug>/<slug:examboard_slug>/<int:pastpaper_id>/<str:pastpaper_name>/model-answers/",
        views.model_answers,
        name="model_answers",
    ),
    # Page that shows a past paper's official mark scheme.
    path(
        "<slug:qualification_slug>/<slug:subject_slug>/<slug:examboard_slug>/<int:pastpaper_id>/<str:pastpaper_name>/mark-scheme/",
        views.mark_scheme,
        name="mark_scheme",
    ),
    # Page for marking a topic as complete.
    path(
        "complete_topic/<int:topic_id>/",
        views.mark_topic_as_complete,
        name="mark_topic_as_complete",
    ),
    # Page for marking a topic as uncomplete.
    path(
        "uncomplete_topic/<int:topic_id>/",
        views.mark_topic_as_uncomplete,
        name="mark_topic_as_uncomplete",
    ),
    # Page for marking a past paper as complete.
    path(
        "complete_pastpaper/<int:pastpaper_id>/",
        views.mark_pastpaper_as_complete,
        name="mark_pastpaper_as_complete",
    ),
    # Page for marking a past paper as uncomplete.
    path(
        "uncomplete_pastpaper/<int:pastpaper_id>/",
        views.mark_pastpaper_as_uncomplete,
        name="mark_pastpaper_as_uncomplete",
    ),
    # Page for adding an exam board to 'My Subjects'.
    path(
        "add_examboard_to_my_subjects/<int:examboard_id>/",
        views.add_examboard_to_my_subjects,
        name="add_examboard_to_my_subjects",
    ),
    # Page for removing an exam board from 'My Subjects'.
    path(
        "remove_examboard_from_my_subjects/<int:examboard_id>/",
        views.remove_examboard_from_my_subjects,
        name="remove_examboard_from_my_subjects",
    ),
]

teachmestem/urls.py
from allauth.account.decorators import secure_admin_login
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

admin.autodiscover()
admin.site.login = secure_admin_login(admin.site.login)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("home.urls")),
    path("tutoring/", include("tutoring.urls")),
    path("courses/", include("courses.urls")),
    path("revise/", include("revision.urls")),
]

if settings.DEBUG:
    from debug_toolbar.toolbar import debug_toolbar_urls

    urlpatterns += debug_toolbar_urls()

tutoring/urls.py
"""Defines URL patterns for tutoring."""

from django.urls import path

from . import views

app_name = "tutoring"

urlpatterns = [
    # Page that shows tutoring info.
    path(
        "",
        views.tutoring,
        name="tutoring",
    ),
    # Page that shows tutoring contact info.
    path(
        "<int:tutor_id>/contact/",
        views.tutoring_contact,
        name="tutoring_contact",
    ),
    # Page that shows tutoring contact form success message.
    path(
        "<int:tutor_id>/contact/sent/",
        views.tutoring_contact_sent,
        name="tutoring_contact_sent",
    ),
]

revision/views.py
from allauth.account.decorators import verified_email_required
from django.contrib.auth.decorators import login_required
from django.http import FileResponse, Http404
from django.shortcuts import render
from django.utils.text import slugify

from .models import (
    ExamBoard,
    PastPaper,
    PastPaperCompletion,
    Qualification,
    Subject,
    Topic,
    TopicCompletion,
    UserExamBoard,
)


@login_required
def qualification(request, qualification_slug):
    """Show all subjects (Subject instances) for a given qualification."""
    qualification = Qualification.objects.get(slug=qualification_slug)
    subjects = Subject.objects.filter(qualification=qualification).order_by(
        "subject_number"
    )
    context = {
        "qualification": qualification,
        "subjects": subjects,
    }
    return render(request, "revision/qualification.html", context)


@login_required
def subject(request, qualification_slug, subject_id, subject_slug):
    """Show all exam boards (ExamBoard instances) for a given subject."""
    subject = Subject.objects.select_related("qualification").get(id=subject_id)
    examboards = ExamBoard.objects.filter(subject=subject)
    context = {
        "subject": subject,
        "examboards": examboards,
    }
    return render(request, "revision/subject.html", context)


@login_required
def examboard(request, qualification_slug, subject_slug, examboard_id, examboard_slug):
    """Show all topics (Topic instances) and past papers (PastPaper instances) for a
    given ExamBoard instance.
    """
    examboard = ExamBoard.objects.select_related(
        "subject", "subject__qualification"
    ).get(id=examboard_id)
    is_examboard_in_my_subjects = UserExamBoard.objects.filter(
        user=request.user, examboard=examboard
    ).exists()
    topics = Topic.objects.filter(examboard=examboard)
    pastpapers = PastPaper.objects.filter(examboard=examboard)
    completed_topics = Topic.objects.filter(
        examboard=examboard,
        topiccompletion__user=request.user,
        topiccompletion__topic__in=topics,
        topiccompletion__is_complete=True,
    )
    completed_pastpapers = PastPaper.objects.filter(
        examboard=examboard,
        pastpapercompletion__user=request.user,
        pastpapercompletion__pastpaper__in=pastpapers,
        pastpapercompletion__is_complete=True,
    )
    num_topics_completed = completed_topics.count()
    num_pastpapers_completed = completed_pastpapers.count()
    total_num_topics = topics.count()
    total_num_pastpapers = pastpapers.count()
    topic_progress_percentage = (
        int(100 * num_topics_completed / total_num_topics)
        if total_num_topics > 0
        else 0
    )
    pastpaper_progress_percentage = (
        int(100 * num_pastpapers_completed / total_num_pastpapers)
        if total_num_pastpapers > 0
        else 0
    )
    context = {
        "examboard": examboard,
        "is_examboard_in_my_subjects": is_examboard_in_my_subjects,
        "topics": topics,
        "pastpapers": pastpapers,
        "completed_topics": completed_topics,
        "completed_pastpapers": completed_pastpapers,
        "num_topics_completed": num_topics_completed,
        "num_pastpapers_completed": num_pastpapers_completed,
        "total_num_topics": total_num_topics,
        "total_num_pastpapers": total_num_pastpapers,
        "topic_progress_percentage": topic_progress_percentage,
        "pastpaper_progress_percentage": pastpaper_progress_percentage,
    }
    if (
        examboard.subject.name == "Maths"
        and examboard.subject.qualification.name == "A Level"
    ):
        context["maths_pure_topics"] = topics.filter(maths_section="pure")
        context["maths_statistics_topics"] = topics.filter(maths_section="statistics")
        context["maths_mechanics_topics"] = topics.filter(maths_section="mechanics")
        return render(request, "revision/examboard_maths.html", context)
    return render(request, "revision/examboard.html", context)


@login_required
def my_subjects(request):
    """Show all exam boards (ExamBoard instances) added to 'My Subjects' by User."""
    my_subjects = UserExamBoard.objects.select_related(
        "examboard", "examboard__subject", "examboard__subject__qualification"
    ).filter(user=request.user)
    context = {
        "my_subjects": my_subjects,
    }
    return render(request, "revision/my_subjects.html", context)


@login_required
def add_examboard_to_my_subjects(request, examboard_id):
    """Add ExamBoard to 'My Subjects' (create UserExamBoard instance)."""
    if request.method != "POST":
        raise Http404
    if UserExamBoard.objects.filter(
        user=request.user, examboard__id=examboard_id
    ).exists():
        raise Http404
    is_examboard_in_my_subjects = True
    examboard = ExamBoard.objects.get(id=examboard_id)
    UserExamBoard.objects.create(user=request.user, examboard=examboard)
    context = {
        "is_examboard_in_my_subjects": is_examboard_in_my_subjects,
        "examboard": examboard,
    }
    return render(request, "revision/snippets/my_subjects_btns.html", context)


@login_required
def remove_examboard_from_my_subjects(request, examboard_id):
    """Remove ExamBoard from 'My Subjects' (delete UserExamBoard instance)."""
    if request.method != "POST":
        raise Http404
    if not UserExamBoard.objects.filter(
        user=request.user, examboard__id=examboard_id
    ).exists():
        raise Http404
    is_examboard_in_my_subjects = False
    examboard = ExamBoard.objects.get(id=examboard_id)
    my_subject = UserExamBoard.objects.get(user=request.user, examboard=examboard)
    my_subject.delete()
    context = {
        "is_examboard_in_my_subjects": is_examboard_in_my_subjects,
        "examboard": examboard,
    }
    return render(request, "revision/snippets/my_subjects_btns.html", context)


@login_required
def mark_topic_as_complete(request, topic_id):
    """Update Topic as complete for User (update or create TopicCompletion instance)."""
    if request.method != "POST":
        raise Http404
    if TopicCompletion.objects.filter(
        user=request.user, topic__id=topic_id, is_complete=True
    ).exists():
        raise Http404
    is_request_htmx = request.headers.get("HX-Request") == "true"
    topic = Topic.objects.select_related(
        "examboard", "examboard__subject", "examboard__subject__qualification"
    ).get(id=topic_id)
    examboard = topic.examboard
    topic_completion = TopicCompletion.objects.get_or_create(
        user=request.user, topic=topic, is_complete=False
    )[0]
    topic_completion.is_complete = True
    topic_completion.save()
    num_topics_completed = TopicCompletion.objects.filter(
        user=request.user, topic__examboard=topic.examboard, is_complete=True
    ).count()
    total_num_topics = Topic.objects.filter(examboard=topic.examboard).count()
    topic_progress_percentage = (
        int(100 * num_topics_completed / total_num_topics)
        if total_num_topics > 0
        else 0
    )
    context = {
        "is_request_htmx": is_request_htmx,
        "topic": topic,
        "examboard": examboard,
        "num_topics_completed": num_topics_completed,
        "total_num_topics": total_num_topics,
        "topic_progress_percentage": topic_progress_percentage,
    }
    return render(request, "revision/snippets/complete_topic_card.html", context)


@login_required
def mark_topic_as_uncomplete(request, topic_id):
    """Update Topic as uncomplete for User (update TopicCompletion instance)."""
    if request.method != "POST":
        raise Http404
    if (
        not TopicCompletion.objects.filter(
            user=request.user, topic__id=topic_id, is_complete=True
        ).exists()
        or TopicCompletion.objects.filter(
            user=request.user, topic__id=topic_id, is_complete=False
        ).exists()
    ):
        raise Http404
    is_request_htmx = request.headers.get("HX-Request") == "true"
    topic = Topic.objects.select_related(
        "examboard", "examboard__subject", "examboard__subject__qualification"
    ).get(id=topic_id)
    examboard = topic.examboard
    topic_completion = TopicCompletion.objects.get(
        user=request.user, topic=topic, is_complete=True
    )
    topic_completion.is_complete = False
    topic_completion.save()
    num_topics_completed = TopicCompletion.objects.filter(
        user=request.user, topic__examboard=topic.examboard, is_complete=True
    ).count()
    total_num_topics = Topic.objects.filter(examboard=topic.examboard).count()
    topic_progress_percentage = (
        int(100 * num_topics_completed / total_num_topics)
        if total_num_topics > 0
        else 0
    )
    context = {
        "is_request_htmx": is_request_htmx,
        "topic": topic,
        "examboard": examboard,
        "num_topics_completed": num_topics_completed,
        "total_num_topics": total_num_topics,
        "topic_progress_percentage": topic_progress_percentage,
    }
    return render(request, "revision/snippets/uncomplete_topic_card.html", context)


@login_required
def mark_pastpaper_as_complete(request, pastpaper_id):
    """Update PastPaper as complete for User (update or create PastPaperCompletion instance)."""
    if request.method != "POST":
        raise Http404
    if PastPaperCompletion.objects.filter(
        user=request.user, pastpaper__id=pastpaper_id, is_complete=True
    ).exists():
        raise Http404
    is_request_htmx = request.headers.get("HX-Request") == "true"
    pastpaper = PastPaper.objects.select_related(
        "examboard", "examboard__subject", "examboard__subject__qualification"
    ).get(id=pastpaper_id)
    examboard = pastpaper.examboard
    pastpaper_completion = PastPaperCompletion.objects.get_or_create(
        user=request.user, pastpaper=pastpaper, is_complete=False
    )[0]
    pastpaper_completion.is_complete = True
    pastpaper_completion.save()

revision/templates/revision/snippets/add_to_my_subjects_btn.html
<button 
    hx-post="{% url 'revision:add_examboard_to_my_subjects' examboard.id %}" 
    hx-target="#my-subjects-btns" hx-swap="outerHTML" hx-push-url="false"
    class="align-self-center btn btn-mysubjects-add rounded-pill border-0 px-4 py-2">
    + Add to My Subjects
</button>

revision/templates/revision/snippets/complete_pastpaper_row.html
{% load static %}
<!-- pastpaper row -->
<tr id="row-div-{{ pastpaper.id }}" class="row-pastpaper-complete">
    <th scope="row">
        <h5 class="mt-1">{{ pastpaper.name | date:'F Y' }}</h5>
    </th>
    <td>
        <a 
            href="{% url 'revision:past_paper' examboard.subject.qualification.slug examboard.subject.slug examboard.slug pastpaper.id pastpaper.name %}" 
            class="btn btn-primary-tms rounded-pill border-0">Paper {{ pastpaper.paper_number }}</a>                       
    </td>
    <td>
        <a 
            href="{% url 'revision:model_answers' examboard.subject.qualification.slug examboard.subject.slug examboard.slug pastpaper.id pastpaper.name %}" 
            class="btn btn-primary-tms rounded-pill border-0">Model Answers</a>
    </td>
    <td>
        <a 
            href="{% url 'revision:mark_scheme' examboard.subject.qualification.slug examboard.subject.slug examboard.slug pastpaper.id pastpaper.name %}" 
            class="btn btn-primary-tms rounded-pill border-0">Mark Scheme</a>
    </td>
    <td class="align-middle">
        <a 
            href="#" hx-target="#row-div-{{ pastpaper.id }}" hx-swap="outerHTML" hx-post="{% url 'revision:mark_pastpaper_as_uncomplete' pastpaper.id %}" 
            hx-push-url="false">
            <img
                alt="checked checkbox"
                src="{% static 'images/checked_checkbox.svg' %}"
                width="25"
                height="25">   
        </a>     
    </td>
</tr>

<!-- htmx oob swaps -->
{% if is_request_htmx %}
    <!-- pastpaper completion count -->
    <h6 id="pastpaper-completion-count" hx-swap-oob="true" class="d-flex justify-content-center mb-3 text-secondary-emphasis">
        ( {{ num_pastpapers_completed }} / {{ total_num_pastpapers }} )
    </h6>

    <!-- pastpaper progress bar -->
    {% if pastpaper_progress_percentage == 100 %}
    <div id="congratulations-toast" hx-swap-oob="true">{% include 'revision/snippets/congratulations_toast.html' %}</div>
    <div id="pastpaper-progress-bar" hx-swap-oob="true" class="progress-bar bg-success" style="width: {{ pastpaper_progress_percentage }}%"></div>
    {% else %}
    <div id="congratulations-toast" hx-swap-oob="true"></div>
    <div id="pastpaper-progress-bar" hx-swap-oob="true" class="progress-bar progress-bar-striped progress-bar-animated" style="width: {{ pastpaper_progress_percentage }}%"></div>
    {% endif %}
{% endif %}

revision/templates/revision/snippets/complete_topic_card.html
{% load static %}
<!-- topic card -->
<card 
    id="card-div-{{ topic.id }}"
    class="card-topic-complete shadow-lg card rounded-3 text-center border-info pt-1 h-100">
    <div class="card-body">
        <div class="d-flex align-items-center justify-content-between mb-2">
            <div aria-hidden="true" style="color:transparent">
                <img
                    style="visibility: hidden;"
                    alt="hidden checked checkbox"
                    src="{% static 'images/checked_checkbox.svg' %}"
                    width="25"
                    height="25">   
            </div>
            <h6 class="card-subtitle text-body-secondary">Topic {{ topic.topic_number }}</h6>
            <a href="#" hx-target="#card-div-{{ topic.id }}" hx-swap="outerHTML" hx-post="{% url 'revision:mark_topic_as_uncomplete' topic.id %}" hx-push-url="false">
                <img
                    alt="checked checkbox"
                    src="{% static 'images/checked_checkbox.svg' %}"
                    width="25"
                    height="25">   
            </a>     
        </div>
        <h5 class="card-title">{{ topic.topic_name }}</h5>
        <a 
            href="{% url 'revision:notes' examboard.subject.qualification.slug examboard.subject.slug examboard.slug topic.id topic.slug %}" 
            class="btn btn-primary-tms rounded-pill border-0 mx-3 px-4 my-2">
            Notes
        </a>                       
        <a 
            href="{% url 'revision:questions' examboard.subject.qualification.slug examboard.subject.slug examboard.slug topic.id topic.slug %}" 
            class="btn btn-primary-tms rounded-pill border-0 mx-3 px-4 my-2">
            Questions
        </a>
    </div>
</card>

<!-- htmx oob swaps -->
{% if is_request_htmx %}
    <!-- topic completion count -->
    <h6 id="topic-completion-count" hx-swap-oob="true" class="border-none d-flex justify-content-center mb-3 text-secondary-emphasis">
        ( {{ num_topics_completed }} / {{ total_num_topics }} )
    </h6>

    <!-- topic progress bar -->
    {% if topic_progress_percentage == 100 %}
    <div id="congratulations-toast" hx-swap-oob="true">{% include 'revision/snippets/congratulations_toast.html' %}</div>
    <div id="topic-progress-bar" hx-swap-oob="true" class="progress-bar bg-success" style="width: {{ topic_progress_percentage }}%"></div>
    {% else %}
    <div id="congratulations-toast" hx-swap-oob="true"></div>
    <div id="topic-progress-bar" hx-swap-oob="true" class="progress-bar progress-bar-striped progress-bar-animated" style="width: {{ topic_progress_percentage }}%"></div>
    {% endif %}
{% endif %}

revision/templates/revision/snippets/footer.html
{% load static %}
<div class="container">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <p class="col-md-4 text-body-secondary" style="opacity: 0.0;">© 2025 Teach Me STEM, Ltd. All Rights Reserved.</p>
        <a 
            href="/"
            class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
            <img 
                alt="revision app home"
                src="{% static 'images/logo.svg' %}"
                width="135"
                height="50.76">
        </a>
        <ul class="nav col-md-4 justify-content-end">
            <li class="nav-item">
                <a href="{% url 'home:privacy' %}" class="nav-link px-2 text-body-secondary">Privacy</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'home:terms' %}" class="nav-link px-2 text-body-secondary">Terms</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'home:contact' %}" class="nav-link px-2 text-body-secondary">Contact</a>
            </li>
        </ul>
    </footer>
</div>

revision/templates/revision/snippets/navbar.html
{% load static %}
<nav class="navbar navbar-dark-color navbar-expand-md mb-4 shadow-lg sticky-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home:index' %}">
            <img 
                alt="Home Page - Teach Me STEM"
                src="{% static 'images/logo.svg' %}"
                width="135"
                height="50.76">
        </a>
        <button 
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarCollapse"
            aria-controls="navbarCollapse"
            aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item dropdown px-1">
                    <a 
                        class="nav-link dropdown-toggle link-body-emphasis"
                        data-bs-toggle="dropdown"
                        aria-expanded="false"
                        role="button"
                        href="{% url 'home:index' %}">Revise</a>
                    <ul class="dropdown-menu">
                        {% for qualification in qualifications %}
                            <li>
                                {% if user.is_authenticated %}
                                    <a 
                                        class="dropdown-item"
                                        href="{% url 'revision:qualification' qualification.slug %}">
                                        {{ qualification.name }}</a>
                                {% else %}
                                    <a 
                                        class="dropdown-item"
                                        href="{% url 'revision:qualification' qualification.slug %}">
                                        {{ qualification.name }}</a>
                                {% endif %}
                            </li>
                        {% endfor %}
                    </ul>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item px-1">
                        <a 
                            class="nav-link link-body-emphasis"
                            href="{% url 'revision:my_subjects' %}">
                            My Subjects</a>                                    
                    </li>
                {% endif %}
                <li class="nav-item px-1">
                    <a 
                        class="nav-link link-body-emphasis"
                        href="{% url 'courses:courses' %}">
                        Courses</a>                                    
                </li>
                <li class="nav-item px-1">
                    <a 
                        class="nav-link link-body-emphasis"
                        href="{% url 'tutoring:tutoring' %}">
                        Tutoring</a>                                    
                </li>
                <li class="nav-item px-1">
                    <a 
                        class="nav-link link-body-emphasis"
                        href="{% url 'home:pricing' %}">
                        Pricing</a>                                    
                </li>
            </ul>
            <ul class="navbar-nav ms-auto mb-2 mb-md-0"> 
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'home:my_account' %}">
                            <img 
                                alt="person icon"
                                src="{% static 'images/person.svg' %}"
                                width="50"
                                height="50"
                                class="me-1">
                        </a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link link-body-emphasis mx-2" href="{% url 'account_login' %}">Sign in</a>
                    </li>
                    <li class="nav-item">
                        <a 
                            class="btn btn-primary-landing rounded-pill border-0 py-2"
                            href="{% url 'account_signup' %}">
                            Join now</a>
                    </li>
                {% endif %}
            </ul> 
        </div>
    </div>
</nav>

revision/templates/revision/snippets/remove_from_my_subjects_btn.html
<button 
    hx-post="{% url 'revision:remove_examboard_from_my_subjects' examboard.id %}" 
    hx-target="#my-subjects-btns" hx-swap="outerHTML" hx-push-url="false"
    class="align-self-center btn btn-mysubjects-remove rounded-pill px-4 py-2">
    - Remove from My Subjects
</button>

revision/templates/revision/snippets/uncomplete_pastpaper_row.html
{% load static %}
<tr id="row-div-{{ pastpaper.id }}">
    <th scope="row">
        <h5 class="mt-1">{{ pastpaper.name | date:'F Y' }}</h5>
    </th>
    <td>
        <a 
            href="{% url 'revision:past_paper' examboard.subject.qualification.slug examboard.subject.slug examboard.slug pastpaper.id pastpaper.name %}" 
            class="btn btn-primary-tms rounded-pill border-0">Paper {{ pastpaper.paper_number }}</a>                       
    </td>
    <td>
        <a 
            href="{% url 'revision:model_answers' examboard.subject.qualification.slug examboard.subject.slug examboard.slug pastpaper.id pastpaper.name %}" 
            class="btn btn-primary-tms rounded-pill border-0">Model Answers</a>
    </td>
    <td>
        <a 
            href="{% url 'revision:mark_scheme' examboard.subject.qualification.slug examboard.subject.slug examboard.slug pastpaper.id pastpaper.name %}" 
            class="btn btn-primary-tms rounded-pill border-0">Mark Scheme</a>
    </td>
    <td class="align-middle">
        <a 
            href="#" hx-target="#row-div-{{ pastpaper.id }}" hx-swap="outerHTML" hx-post="{% url 'revision:mark_pastpaper_as_complete' pastpaper.id %}" 
            hx-push-url="false">
            <img
                alt="unchecked checkbox"
                src="{% static 'images/unchecked_checkbox.svg' %}"
                width="25"
                height="25">   
        </a>      
    </td>
</tr>

<!-- htmx oob swaps -->
{% if is_request_htmx %}
    <!-- pastpaper completion count -->
    <h6 id="pastpaper-completion-count" hx-swap-oob="true" class="border-none d-flex justify-content-center mb-3 text-secondary-emphasis">
        ( {{ num_pastpapers_completed }} / {{ total_num_pastpapers }} )
    </h6>

    <!-- pastpaper progress bar -->
    <div id="pastpaper-progress-bar" hx-swap-oob="true" class="progress-bar progress-bar-striped progress-bar-animated" style="width: {{ pastpaper_progress_percentage }}%"></div>

    <!-- congratulations toast -->
    <div id="congratulations-toast" hx-swap-oob="true"></div>
{% endif %}