courses/urls.py
"""Defines URL patterns for courses."""

from django.urls import path

from . import views

app_name = "courses"

urlpatterns = [
    # Page that shows courses info.
    path(
        "",
        views.courses,
        name="courses",
    ),
    # Page that shows course registration info and form.
    path(
        "<int:course_id>/register/",
        views.courses_register,
        name="courses_register",
    ),
    # Page that shows course registration form success message.
    path(
        "<int:course_id>/register/success/",
        views.courses_register_success,
        name="courses_register_success",
    ),
]

home/urls.py
"""Defines URL patterns for home."""

from django.urls import path

from . import views

app_name = "home"
urlpatterns = [
    # Home page.
    path("", views.index, name="index"),
    # Page that shows privacy info.
    path(
        "privacy/",
        views.privacy,
        name="privacy",
    ),
    # Page that shows terms info.
    path(
        "terms/",
        views.terms,
        name="terms",
    ),
    # Page that shows contact info and form.
    path(
        "contact/",
        views.contact,
        name="contact",
    ),
    # Page that shows contact form success message.
    path(
        "contact/sent/",
        views.contact_sent,
        name="contact_sent",
    ),
    # Page that shows options relating to account for logged in users.
    path("my-account/", views.my_account, name="my_account"),
    # Page that shows pricing info.
    path("pricing/", views.pricing, name="pricing"),
]

teachmestem/urls.py
from allauth.account.decorators import secure_admin_login
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

admin.autodiscover()
admin.site.login = secure_admin_login(admin.site.login)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("home.urls")),
    path("tutoring/", include("tutoring.urls")),
    path("courses/", include("courses.urls")),
    path("revise/", include("revision.urls")),
]

if settings.DEBUG:
    from debug_toolbar.toolbar import debug_toolbar_urls

    urlpatterns += debug_toolbar_urls()

courses/models.py
from django.contrib.auth.models import User
from django.db import models

from revision.models import ExamBoard


class Course(models.Model):
    """A course ran by an instructor for a given ExamBoard instance."""

    examboard = models.ForeignKey(ExamBoard, on_delete=models.CASCADE)
    instructor = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
    price = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        """Return a string representation of the model."""
        return f"{self.examboard} course ran by {self.instructor} on {self.date}"


class CourseRegisterUser(models.Model):
    """A user who registers for a Course via the CourseRegisterForm."""

    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    email = models.EmailField()

    def __str__(self):
        """Return a string representation of the model."""
        return f"{self.first_name} {self.last_name}"

courses/forms.py
from django import forms
from django_recaptcha.fields import ReCaptchaField
from django_recaptcha.widgets import ReCaptchaV3

from .models import CourseRegisterUser


class CourseRegisterForm(forms.ModelForm):
    captcha = ReCaptchaField(widget=ReCaptchaV3)

    class Meta:
        model = CourseRegisterUser
        fields = [
            "course",
            "first_name",
            "last_name",
            "email",
        ]
        labels = {
            "email": "Email address",
        }

courses/views.py
from django.core.mail import send_mail
from django.shortcuts import redirect, render


from .forms import CourseRegisterForm
from .models import Course


def courses(request):
    """Show courses page."""
    courses = Course.objects.select_related(
        "instructor",
        "examboard",
        "examboard__subject",
        "examboard__subject__qualification",
    ).order_by("date", "examboard__subject__name")
    context = {
        "courses": courses,
    }
    return render(request, "courses/courses.html", context)


def courses_register(request, course_id):
    """Show course registration page."""
    course = Course.objects.select_related(
        "examboard",
        "examboard__subject",
        "examboard__subject__qualification",
        "instructor",
    ).get(id=course_id)
    if request.method != "POST":
        form = CourseRegisterForm()
    else:
        form = CourseRegisterForm(data=request.POST)
        if form.is_valid():
            send_mail(
                subject=f"{form.cleaned_data['first_name']} {form.cleaned_data['last_name']} has registered interest in a course!",
                message=f"""Requested course: {course.examboard.subject.qualification} {course.examboard.subject} {course.examboard}
                    Course date: {course.date}
                    Course instructor: {course.instructor}
                    Course price: £{course.price}
                    Name: {form.cleaned_data["first_name"]} {form.cleaned_data["last_name"]} 
                    Email: {form.cleaned_data["email"]}
                    """,
                from_email=None,
                recipient_list=[],
            )
            form.save()
            return redirect("courses:courses_register_success", course_id)

    context = {
        "course": course,
        "form": form,
    }
    return render(request, "courses/courses_register.html", context)


def courses_register_success(request, course_id):
    """Show course registration form success page."""
    return render(request, "courses/courses_register_success.html")

courses/templates/courses/courses.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}
    Courses ·
{% endblock title %}
{% block breadcrumb %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a 
                    href="{% url 'home:index' %}"
                    class="text-info link-secondary link-underline-opacity-0">
                    Home
                </a>
            </li>
            <li class="breadcrumb-item" aria-current="page">Courses</li>
        </ol>
    </nav>
{% endblock breadcrumb %}
{% block page_header %}
    <h1 class="border-none pb-2 my-3 d-flex justify-content-center display-5 fw-bold text-body-emphasis">Courses</h1>
{% endblock page_header %}
{% block content_1 %}
<h5 class="border-none border-3 my-0 mb-5 d-flex justify-content-center">Choose from our courses below.</h5>
    <div class="row row-cols-1 g-4">
        {% for course in courses %}
            <div class="col-sm-6 mb-3 mb-sm-0">
                <a 
                    class="btn-card shadow-lg card btn btn-primary px-0 py-0  rounded-3 text-center border border-info h-100"
                    href="{% url 'courses:courses_register' course.id %}">
                    <div class="card-header border-0 pt-4">
                        <img
                            class="card-img-top"
                            alt="course subject symbol"
                            src="{% static 'images/'|add:course.examboard.subject.slug|add:'.svg' %}"
                            width="90"
                            height="90">
                        <h6 class="card-subtitle text-body-secondary pt-4 pb-2">{{ course.examboard.subject.qualification }} · {{ course.examboard }}</h6>
                        <h5 class="mt-2 card-title">{{ course.examboard.subject }}</h5>
                    </div>
                    <div class="card-body">
                        <h5 class="mt-3 card-title">🗓️ {{ course.date|date:"j F Y" }}</h5>
                        <h5 class="mt-3 card-title">💷 £{{ course.price|floatformat:0 }}</h5>
                        <h5 class="mt-3 card-title">🎓 Dr {{ course.instructor.first_name|title }}</h5>
                    </div>
                </a>
            </div>
        {% endfor %}            
{% endblock content_1 %}

courses/templates/courses/courses_register.html
{% extends 'home/base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block title %}
    Course Registration ·
{% endblock title %}
{% block breadcrumb %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a 
                    href="{% url 'home:index' %}"
                    class="text-info link-secondary link-underline-opacity-0">
                    Home
                </a>
            </li>
            <li class="breadcrumb-item">
                <a 
                    href="{% url 'courses:courses' %}"
                    class="text-info link-secondary link-underline-opacity-0">
                    Courses
                </a>
            </li>
            <li class="breadcrumb-item" aria-current="page">Register</li>
        </ol>
    </nav>
{% endblock breadcrumb %}
{% block page_header %}
    <h1 class="border-none pb-2 my-3 d-flex justify-content-center display-5 fw-bold text-body-emphasis">Course Registration</h1>
{% endblock page_header %}
{% block content_1 %}
    <div class="container">
        <p class="d-flex justify-content-center mb-2">Please fill in the details below to register interest in the course.</p>
        <div class="d-flex justify-content-center my-5">
            <div 
                class="rounded-5 text-center h-100 py-4 px-5"
                href="{% url 'courses:courses_register' course.id %}">
                <h5 class="d-flex justify-content-center fw-semibold mb-2">Course</h5>
                <div class="card-header border-0 pt-4">
                    <img
                        class="card-img-top"
                        alt="course subject symbol"
                        src="{% static 'images/'|add:course.examboard.subject.slug|add:'.svg' %}"
                        width="90"
                        height="90">
                    <h6 class="card-subtitle text-body-secondary pt-4 pb-2">{{ course.examboard.subject.qualification }} · {{ course.examboard }}</h6>
                    <h5 class="mt-2 card-title">{{ course.examboard.subject }}</h5>
                </div>
                <div class="card-body">
                    <h5 class="mt-3 card-title">🗓️ {{ course.date|date:"j F Y" }}</h5>
                    <h5 class="mt-3 card-title">💷 £{{ course.price|floatformat:0 }}</h5>
                    <h5 class="mt-3 card-title">🎓 Dr {{ course.instructor.first_name|title }}</h5>
                </div>
            </div>
        </div>
        <div class="d-flex justify-content-center">            
            <form action="{% url 'courses:courses_register' course.id %}" method='post'
                style="min-width: 35%;">
                {% csrf_token %}
                <input type="hidden" name="course" maxlength="200" class="form-control" required id="id_course" value="{{ course.id }}">
                {% bootstrap_form form exclude="course" layout="floating" %}
                <div class="d-flex justify-content-center mt-4">
                    <button class="btn btn-primary-tms rounded-pill px-4 py-2 border-0" type="submit">Register</button>
                </div>
            </form>
        </div>
    </div>
{% endblock content_1 %}

courses/templates/courses/courses_register_success.html
{% extends 'courses/courses_register.html' %}
{% block content_1 %}
    <div class="container">
        <h2 class="mt-5 py-3 d-flex justify-content-center">
            Thank you for registering interest!
        </h2>
        <h2 class="mt-5 py-3 d-flex justify-content-center">
            We'll get back to you with more details closer to the date.
        </h2>
    </div>
{% endblock content_1 %}