courses/urls.py
"""Defines URL patterns for courses."""

from django.urls import path

from . import views

app_name = "courses"

urlpatterns = [
    # Page that shows courses info.
    path(
        "",
        views.courses,
        name="courses",
    ),
    # Page that shows course registration info and form.
    path(
        "<int:course_id>/register/",
        views.courses_register,
        name="courses_register",
    ),
    # Page that shows course registration form success message.
    path(
        "<int:course_id>/register/success/",
        views.courses_register_success,
        name="courses_register_success",
    ),
]

home/urls.py
"""Defines URL patterns for home."""

from django.urls import path

from . import views

app_name = "home"
urlpatterns = [
    # Home page.
    path("", views.index, name="index"),
    # Page that shows privacy info.
    path(
        "privacy/",
        views.privacy,
        name="privacy",
    ),
    # Page that shows terms info.
    path(
        "terms/",
        views.terms,
        name="terms",
    ),
    # Page that shows contact info and form.
    path(
        "contact/",
        views.contact,
        name="contact",
    ),
    # Page that shows contact form success message.
    path(
        "contact/sent/",
        views.contact_sent,
        name="contact_sent",
    ),
    # Page that shows options relating to account for logged in users.
    path("my-account/", views.my_account, name="my_account"),
    # Page that shows pricing info.
    path("pricing/", views.pricing, name="pricing"),
]

revision/urls.py
"""Defines URL patterns for revision."""

from django.urls import path

from . import views

app_name = "revision"
urlpatterns = [
    # Page that shows 'My Subjects' for logged in users.
    path(
        "my-subjects/",
        views.my_subjects,
        name="my_subjects",
    ),
    # Page that shows subjects for a given qualification.
    path(
        "<slug:qualification_slug>/",
        views.qualification,
        name="qualification",
    ),
    # Page that show exam boards for a given subject.
    path(
        "<slug:qualification_slug>/<int:subject_id>/<slug:subject_slug>/",
        views.subject,
        name="subject",
    ),
    # Page that shows links to revision notes, questions, and past papers for a given exam board.
    path(
        "<slug:qualification_slug>/<slug:subject_slug>/<int:examboard_id>/<slug:examboard_slug>/",
        views.examboard,
        name="examboard",
    ),
    # Page that shows notes belonging to a topic.
    path(
        "<slug:qualification_slug>/<slug:subject_slug>/<slug:examboard_slug>/<int:topic_id>/<slug:topic_slug>/notes/",
        views.notes,
        name="notes",
    ),
    # Page that shows questions belonging to a topic.
    path(
        "<slug:qualification_slug>/<slug:subject_slug>/<slug:examboard_slug>/<int:topic_id>/<slug:topic_slug>/questions/",
        views.questions,
        name="questions",
    ),
    # Page that shows a past paper belonging to an exam board.
    path(
        "<slug:qualification_slug>/<slug:subject_slug>/<slug:examboard_slug>/<int:pastpaper_id>/<str:pastpaper_name>/past-paper/",
        views.past_paper,
        name="past_paper",
    ),
    # Page that shows a past paper's model answers.
    path(
        "<slug:qualification_slug>/<slug:subject_slug>/<slug:examboard_slug>/<int:pastpaper_id>/<str:pastpaper_name>/model-answers/",
        views.model_answers,
        name="model_answers",
    ),
    # Page that shows a past paper's official mark scheme.
    path(
        "<slug:qualification_slug>/<slug:subject_slug>/<slug:examboard_slug>/<int:pastpaper_id>/<str:pastpaper_name>/mark-scheme/",
        views.mark_scheme,
        name="mark_scheme",
    ),
    # Page for marking a topic as complete.
    path(
        "complete_topic/<int:topic_id>/",
        views.mark_topic_as_complete,
        name="mark_topic_as_complete",
    ),
    # Page for marking a topic as uncomplete.
    path(
        "uncomplete_topic/<int:topic_id>/",
        views.mark_topic_as_uncomplete,
        name="mark_topic_as_uncomplete",
    ),
    # Page for marking a past paper as complete.
    path(
        "complete_pastpaper/<int:pastpaper_id>/",
        views.mark_pastpaper_as_complete,
        name="mark_pastpaper_as_complete",
    ),
    # Page for marking a past paper as uncomplete.
    path(
        "uncomplete_pastpaper/<int:pastpaper_id>/",
        views.mark_pastpaper_as_uncomplete,
        name="mark_pastpaper_as_uncomplete",
    ),
    # Page for adding an exam board to 'My Subjects'.
    path(
        "add_examboard_to_my_subjects/<int:examboard_id>/",
        views.add_examboard_to_my_subjects,
        name="add_examboard_to_my_subjects",
    ),
    # Page for removing an exam board from 'My Subjects'.
    path(
        "remove_examboard_from_my_subjects/<int:examboard_id>/",
        views.remove_examboard_from_my_subjects,
        name="remove_examboard_from_my_subjects",
    ),
]

teachmestem/urls.py
from allauth.account.decorators import secure_admin_login
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

admin.autodiscover()
admin.site.login = secure_admin_login(admin.site.login)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("home.urls")),
    path("tutoring/", include("tutoring.urls")),
    path("courses/", include("courses.urls")),
    path("revise/", include("revision.urls")),
]

if settings.DEBUG:
    from debug_toolbar.toolbar import debug_toolbar_urls

    urlpatterns += debug_toolbar_urls()

tutoring/urls.py
"""Defines URL patterns for tutoring."""

from django.urls import path

from . import views

app_name = "tutoring"

urlpatterns = [
    # Page that shows tutoring info.
    path(
        "",
        views.tutoring,
        name="tutoring",
    ),
    # Page that shows tutoring contact info.
    path(
        "<int:tutor_id>/contact/",
        views.tutoring_contact,
        name="tutoring_contact",
    ),
    # Page that shows tutoring contact form success message.
    path(
        "<int:tutor_id>/contact/sent/",
        views.tutoring_contact_sent,
        name="tutoring_contact_sent",
    ),
]

revision/views.py
from allauth.account.decorators import verified_email_required
from django.contrib.auth.decorators import login_required
from django.http import FileResponse, Http404
from django.shortcuts import render
from django.utils.text import slugify

from .models import (
    ExamBoard,
    PastPaper,
    PastPaperCompletion,
    Qualification,
    Subject,
    Topic,
    TopicCompletion,
    UserExamBoard,
)


@login_required
def qualification(request, qualification_slug):
    """Show all subjects (Subject instances) for a given qualification."""
    qualification = Qualification.objects.get(slug=qualification_slug)
    subjects = Subject.objects.filter(qualification=qualification).order_by(
        "subject_number"
    )
    context = {
        "qualification": qualification,
        "subjects": subjects,
    }
    return render(request, "revision/qualification.html", context)


@login_required
def subject(request, qualification_slug, subject_id, subject_slug):
    """Show all exam boards (ExamBoard instances) for a given subject."""
    subject = Subject.objects.select_related("qualification").get(id=subject_id)
    examboards = ExamBoard.objects.filter(subject=subject)
    context = {
        "subject": subject,
        "examboards": examboards,
    }
    return render(request, "revision/subject.html", context)


@login_required
def examboard(request, qualification_slug, subject_slug, examboard_id, examboard_slug):
    """Show all topics (Topic instances) and past papers (PastPaper instances) for a
    given ExamBoard instance.
    """
    examboard = ExamBoard.objects.select_related(
        "subject", "subject__qualification"
    ).get(id=examboard_id)
    is_examboard_in_my_subjects = UserExamBoard.objects.filter(
        user=request.user, examboard=examboard
    ).exists()
    topics = Topic.objects.filter(examboard=examboard)
    pastpapers = PastPaper.objects.filter(examboard=examboard)
    completed_topics = Topic.objects.filter(
        examboard=examboard,
        topiccompletion__user=request.user,
        topiccompletion__topic__in=topics,
        topiccompletion__is_complete=True,
    )
    completed_pastpapers = PastPaper.objects.filter(
        examboard=examboard,
        pastpapercompletion__user=request.user,
        pastpapercompletion__pastpaper__in=pastpapers,
        pastpapercompletion__is_complete=True,
    )
    num_topics_completed = completed_topics.count()
    num_pastpapers_completed = completed_pastpapers.count()
    total_num_topics = topics.count()
    total_num_pastpapers = pastpapers.count()
    topic_progress_percentage = (
        int(100 * num_topics_completed / total_num_topics)
        if total_num_topics > 0
        else 0
    )
    pastpaper_progress_percentage = (
        int(100 * num_pastpapers_completed / total_num_pastpapers)
        if total_num_pastpapers > 0
        else 0
    )
    context = {
        "examboard": examboard,
        "is_examboard_in_my_subjects": is_examboard_in_my_subjects,
        "topics": topics,
        "pastpapers": pastpapers,
        "completed_topics": completed_topics,
        "completed_pastpapers": completed_pastpapers,
        "num_topics_completed": num_topics_completed,
        "num_pastpapers_completed": num_pastpapers_completed,
        "total_num_topics": total_num_topics,
        "total_num_pastpapers": total_num_pastpapers,
        "topic_progress_percentage": topic_progress_percentage,
        "pastpaper_progress_percentage": pastpaper_progress_percentage,
    }
    if (
        examboard.subject.name == "Maths"
        and examboard.subject.qualification.name == "A Level"
    ):
        context["maths_pure_topics"] = topics.filter(maths_section="pure")
        context["maths_statistics_topics"] = topics.filter(maths_section="statistics")
        context["maths_mechanics_topics"] = topics.filter(maths_section="mechanics")
        return render(request, "revision/examboard_maths.html", context)
    return render(request, "revision/examboard.html", context)


@login_required
def my_subjects(request):
    """Show all exam boards (ExamBoard instances) added to 'My Subjects' by User."""
    my_subjects = UserExamBoard.objects.select_related(
        "examboard", "examboard__subject", "examboard__subject__qualification"
    ).filter(user=request.user)
    context = {
        "my_subjects": my_subjects,
    }
    return render(request, "revision/my_subjects.html", context)


@login_required
def add_examboard_to_my_subjects(request, examboard_id):
    """Add ExamBoard to 'My Subjects' (create UserExamBoard instance)."""
    if request.method != "POST":
        raise Http404
    if UserExamBoard.objects.filter(
        user=request.user, examboard__id=examboard_id
    ).exists():
        raise Http404
    is_examboard_in_my_subjects = True
    examboard = ExamBoard.objects.get(id=examboard_id)
    UserExamBoard.objects.create(user=request.user, examboard=examboard)
    context = {
        "is_examboard_in_my_subjects": is_examboard_in_my_subjects,
        "examboard": examboard,
    }
    return render(request, "revision/snippets/my_subjects_btns.html", context)


@login_required
def remove_examboard_from_my_subjects(request, examboard_id):
    """Remove ExamBoard from 'My Subjects' (delete UserExamBoard instance)."""
    if request.method != "POST":
        raise Http404
    if not UserExamBoard.objects.filter(
        user=request.user, examboard__id=examboard_id
    ).exists():
        raise Http404
    is_examboard_in_my_subjects = False
    examboard = ExamBoard.objects.get(id=examboard_id)
    my_subject = UserExamBoard.objects.get(user=request.user, examboard=examboard)
    my_subject.delete()
    context = {
        "is_examboard_in_my_subjects": is_examboard_in_my_subjects,
        "examboard": examboard,
    }
    return render(request, "revision/snippets/my_subjects_btns.html", context)


@login_required
def mark_topic_as_complete(request, topic_id):
    """Update Topic as complete for User (update or create TopicCompletion instance)."""
    if request.method != "POST":
        raise Http404
    if TopicCompletion.objects.filter(
        user=request.user, topic__id=topic_id, is_complete=True
    ).exists():
        raise Http404
    is_request_htmx = request.headers.get("HX-Request") == "true"
    topic = Topic.objects.select_related(
        "examboard", "examboard__subject", "examboard__subject__qualification"
    ).get(id=topic_id)
    examboard = topic.examboard
    topic_completion = TopicCompletion.objects.get_or_create(
        user=request.user, topic=topic, is_complete=False
    )[0]
    topic_completion.is_complete = True
    topic_completion.save()
    num_topics_completed = TopicCompletion.objects.filter(
        user=request.user, topic__examboard=topic.examboard, is_complete=True
    ).count()
    total_num_topics = Topic.objects.filter(examboard=topic.examboard).count()
    topic_progress_percentage = (
        int(100 * num_topics_completed / total_num_topics)
        if total_num_topics > 0
        else 0
    )
    context = {
        "is_request_htmx": is_request_htmx,
        "topic": topic,
        "examboard": examboard,
        "num_topics_completed": num_topics_completed,
        "total_num_topics": total_num_topics,
        "topic_progress_percentage": topic_progress_percentage,
    }
    return render(request, "revision/snippets/complete_topic_card.html", context)


@login_required
def mark_topic_as_uncomplete(request, topic_id):
    """Update Topic as uncomplete for User (update TopicCompletion instance)."""
    if request.method != "POST":
        raise Http404
    if (
        not TopicCompletion.objects.filter(
            user=request.user, topic__id=topic_id, is_complete=True
        ).exists()
        or TopicCompletion.objects.filter(
            user=request.user, topic__id=topic_id, is_complete=False
        ).exists()
    ):
        raise Http404
    is_request_htmx = request.headers.get("HX-Request") == "true"
    topic = Topic.objects.select_related(
        "examboard", "examboard__subject", "examboard__subject__qualification"
    ).get(id=topic_id)
    examboard = topic.examboard
    topic_completion = TopicCompletion.objects.get(
        user=request.user, topic=topic, is_complete=True
    )
    topic_completion.is_complete = False
    topic_completion.save()
    num_topics_completed = TopicCompletion.objects.filter(
        user=request.user, topic__examboard=topic.examboard, is_complete=True
    ).count()
    total_num_topics = Topic.objects.filter(examboard=topic.examboard).count()
    topic_progress_percentage = (
        int(100 * num_topics_completed / total_num_topics)
        if total_num_topics > 0
        else 0
    )
    context = {
        "is_request_htmx": is_request_htmx,
        "topic": topic,
        "examboard": examboard,
        "num_topics_completed": num_topics_completed,
        "total_num_topics": total_num_topics,
        "topic_progress_percentage": topic_progress_percentage,
    }
    return render(request, "revision/snippets/uncomplete_topic_card.html", context)


@login_required
def mark_pastpaper_as_complete(request, pastpaper_id):
    """Update PastPaper as complete for User (update or create PastPaperCompletion instance)."""
    if request.method != "POST":
        raise Http404
    if PastPaperCompletion.objects.filter(
        user=request.user, pastpaper__id=pastpaper_id, is_complete=True
    ).exists():
        raise Http404
    is_request_htmx = request.headers.get("HX-Request") == "true"
    pastpaper = PastPaper.objects.select_related(
        "examboard", "examboard__subject", "examboard__subject__qualification"
    ).get(id=pastpaper_id)
    examboard = pastpaper.examboard
    pastpaper_completion = PastPaperCompletion.objects.get_or_create(
        user=request.user, pastpaper=pastpaper, is_complete=False
    )[0]
    pastpaper_completion.is_complete = True
    pastpaper_completion.save()

tutoring/views.py
from django.core.mail import send_mail
from django.shortcuts import redirect, render


from .forms import TutoringContactForm
from .models import Tutor


def tutoring(request):
    """Show tutoring page."""
    tutors = Tutor.objects.all()
    context = {
        "tutors": tutors,
    }
    return render(request, "tutoring/tutoring.html", context)


def tutoring_contact(request, tutor_id):
    """Show tutoring contact page."""
    tutor = Tutor.objects.get(id=tutor_id)
    if request.method != "POST":
        form = TutoringContactForm()
    else:
        form = TutoringContactForm(data=request.POST)
        if form.is_valid():
            send_mail(
                subject=f"{form.cleaned_data['first_name']} {form.cleaned_data['last_name']} has requested tutoring!",
                message=f"""Requested tutor: {tutor.name}
                    Name: {form.cleaned_data["first_name"]} {form.cleaned_data["last_name"]} 
                    Email: {form.cleaned_data["email"]}
                    Message:
                    
                    {form.cleaned_data["message"]}
                    
                    """,
                from_email=None,
                recipient_list=[],
            )
            form.save()
            return redirect("tutoring:tutoring_contact_sent", tutor_id)

    context = {
        "tutor": tutor,
        "form": form,
    }
    return render(request, "tutoring/tutoring_contact.html", context)


def tutoring_contact_sent(request, tutor_id):
    """Show tutoring contact form success page."""
    return render(request, "tutoring/tutoring_contact_sent.html")

revision/templates/revision/base_examboard.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}
    {{ examboard.name }} {{ examboard.subject.qualification.name }} {{ examboard.subject.name }}  Revision ·
{% endblock title %}
{% block breadcrumb %}
    <div class="d-flex justify-content-between">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a 
                        href="{% url 'home:index' %}"
                        class="link-secondary link-underline-opacity-0 text-info">Home</a>
                </li>
                <li class="breadcrumb-item">
                    <a 
                        href="{% url 'revision:qualification' examboard.subject.qualification.slug %}"
                        class="link-secondary link-underline-opacity-0 text-info">{{ examboard.subject.qualification.name }}</a>
                </li>
                <li class="breadcrumb-item">
                    <a 
                        href="{% url 'revision:subject' examboard.subject.qualification.slug examboard.subject.id examboard.subject.slug %}"
                        class="link-secondary link-underline-opacity-0 text-info">{{ examboard.subject.name }}</a>
                </li>
                <li class="breadcrumb-item" aria-current="page">{{ examboard.name }}</li>
            </ol>
        </nav>
        {% include 'revision/snippets/my_subjects_btns.html' %}
    </div>
{% endblock breadcrumb %}
{% block page_header %}
    <div class="d-flex justify-content-center">
        <img 
            alt="subject symbol"
            src="{% static 'images/'|add:examboard.subject.slug|add:'.svg' %}"
            width="90"
            height="90">
    </div>
    <div class="d-flex justify-content-center">
        <h1 class="my-3 display-5 fw-bold text-body-emphasis">
            {{ examboard.name }} {{ examboard.subject.qualification.name }} {{ examboard.subject.name }}
        </h1>
    </div>
    <div class="d-flex justify-content-center">
        <h5 class="border-none mb-4">Everything you need in one place.</h5>
    </div>
    <div class="my-4">    
        {% include 'revision/snippets/topic_progress_bar.html' %}
    </div>
    <div id="congratulations-toast"></div>
{% endblock page_header %}
{% block content_1 %}
    {% block topics %}
    {% endblock topics %}
    
    {% block topics_maths_pure %}
    {% endblock topics_maths_pure %}

    {% block topics_maths_statistics %}
    {% endblock topics_maths_statistics %}

    {% block topics_maths_mechanics %}
    {% endblock topics_maths_mechanics %}

    {% block pastpapers %}
    {% endblock pastpapers %}
{% endblock content_1 %}

revision/templates/revision/contact.html
{% extends 'revision/base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block title %}
    Contact ·
{% endblock title %}
{% block breadcrumb %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a 
                    href="{% url 'home:index' %}"
                    class="text-info link-secondary link-underline-opacity-0">
                    Home
                </a>
            </li>
            <li class="breadcrumb-item" aria-current="page">Contact</li>
        </ol>
    </nav>
{% endblock breadcrumb %}
{% block page_header %}
    <h1 class="border-none pb-2 my-3 d-flex justify-content-center display-5 fw-bold text-body-emphasis">Contact</h1>
{% endblock page_header %}
{% block content_1 %}
    <div class="container">
        <p class="d-flex justify-content-center mb-4">Please fill in the details below to get in touch with us.</p>
        <div class="d-flex justify-content-center">
            <form action="{% url 'home:contact' %}" method='post'>
                {% csrf_token %}
                {% bootstrap_form form layout="floating" %}
                <div class="d-flex justify-content-center">
                    <button class="btn btn-primary-tms rounded-pill px-4 py-2 border-0" type="submit">Send</button>
                </div>
            </form>
        </div>
    </div>
{% endblock content_1 %}

revision/templates/revision/my_subjects.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}
    My Subjects ·
{% endblock title %}
{% block breadcrumb %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a 
                    href="{% url 'home:index' %}"
                    class="link-secondary link-underline-opacity-0 text-info">Home</a>
            </li>
            <li class="breadcrumb-item" aria-current="page">My Subjects</li>
        </ol>
    </nav>
{% endblock breadcrumb %}
{% block page_header %}
    <h1 class="border-none pb-2 my-3 d-flex justify-content-center display-5 fw-bold text-body-emphasis">My Subjects</h1>
    <h5 class="border-none my-0 mb-5 d-flex justify-content-center">Quickly access your revision material.</h5>
{% endblock page_header %}
{% block content_1 %}
    <div class="row row-cols-1 g-4">
        {% if not my_subjects %}
            <div class="py-5 my-5">
                <h5 class="border-none my-0 mb-5 d-flex justify-content-center">
                    No subjects added yet!
                </h5>
            </div>
        {% endif %}   
        {% for my_subject in my_subjects %}
            <div class="col-sm-6 mb-3 mb-sm-0">
                <a 
                    class="btn-card shadow-lg card btn btn-primary rounded-3 text-center border border-info pt-4 h-100"
                    href="{% url 'revision:examboard' my_subject.examboard.subject.qualification.slug my_subject.examboard.subject.slug my_subject.examboard.id my_subject.examboard.slug %}">
                    <img 
                        class="card-img-top"
                        alt="subject symbol"
                        src="{% static 'images/'|add:my_subject.examboard.subject.slug|add:'.svg' %}"
                        width="90"
                        height="90">
                    <div class="card-body">
                        <h6 class="card-subtitle text-body-secondary py-2">{{ my_subject.examboard.subject.qualification.name }} · {{ my_subject.examboard.name }}</h6>
                        <h5 class="mt-2 card-title">{{ my_subject.examboard.subject.name }}</h5>
                        <div class="d-flex justify-content-center">
                            {% include 'revision/snippets/my_subjects_progress_bar.html' %}
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock content_1 %}

revision/templates/revision/notes.html
{% extends 'home/base.html' %} 
{% load static %}
{% block title %}
    {{topic.examboard.name}} {{ topic.examboard.subject.qualification.name }} {{ topic.examboard.subject.name }} Topic {{topic.topic_number}} Notes ·
{% endblock title %}
{% block breadcrumb %}
    <div class="d-flex justify-content-between">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a 
                        href="{% url 'home:index' %}"
                        class="link-secondary link-underline-opacity-0 text-info">Home</a>
                </li>
                <li class="breadcrumb-item">
                    <a 
                        href="{% url 'revision:qualification' topic.examboard.subject.qualification.slug %}"
                        class="link-secondary link-underline-opacity-0 text-info">{{ topic.examboard.subject.qualification.name }}</a>
                </li>
                <li class="breadcrumb-item">
                    <a 
                        href="{% url 'revision:subject' topic.examboard.subject.qualification.slug topic.examboard.subject.id topic.examboard.subject.slug %}"
                        class="link-secondary link-underline-opacity-0 text-info">{{ topic.examboard.subject.name }}</a>
                </li>
                <li class="breadcrumb-item">
                    <a 
                        href="{% url 'revision:examboard' topic.examboard.subject.qualification.slug topic.examboard.subject.slug topic.examboard.id topic.examboard.slug %}"
                        class="link-secondary link-underline-opacity-0 text-info">{{ topic.examboard.name  }}</a>
                </li>
                <li class="breadcrumb-item" aria-current="page">Topic {{ topic.topic_number }} : {{topic.topic_name}} - Notes</li>
            </ol>
        </nav>
    </div>
{% endblock breadcrumb %}
{% block page_header %}
    <h5 class="mt-3 mb-0 d-flex justify-content-center text-body-secondary">
        Topic {{ topic.topic_number }}
    </h5>
    <h1 class="d-flex justify-content-center text-body-emphasis display-5 fw-bold mt-4 mb-5 py-2">
        {{ topic.topic_name }}
    </h1>
{% endblock page_header %}

{% block content_notes %}
    {% include notes_template_name %}
{% endblock content_notes %}
{% block button_group_notes %}
    <div class="d-flex justify-content-between">
        {% if prev_topic is not None %}
            <a 
                href="{% url 'revision:notes' topic.examboard.subject.qualification.slug topic.examboard.subject.slug topic.examboard.slug prev_topic.id prev_topic.slug %}" 
                class="btn btn-primary-tms rounded-pill border-0 mx-3 px-4 py-2 my-2">Previous topic</a>                       
        {% endif %}
        <a 
            href="{% url 'revision:questions' topic.examboard.subject.qualification.slug topic.examboard.subject.slug topic.examboard.slug topic.id topic.slug %}" 
            class="btn btn-primary-tms rounded-pill border-0 mx-3 px-4 py-2 my-2">Questions</a>
        {% if next_topic is not None %}
            <a 
                href="{% url 'revision:notes' topic.examboard.subject.qualification.slug topic.examboard.subject.slug topic.examboard.slug next_topic.id next_topic.slug %}" 
                class="btn btn-primary-tms rounded-pill border-0 mx-3 px-4 py-2 my-2">Next topic</a>                       
        {% endif %}
        </div>
{% endblock button_group_notes %}

revision/templates/revision/subject.html
{% extends 'home/base.html' %}
{% load static %}
{% block title %}
    {{ subject.qualification.name }} {{ subject.name }} Revision ·
{% endblock title %}
{% block breadcrumb %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a 
                    href="{% url 'home:index' %}"
                    class="link-secondary link-underline-opacity-0 text-info">Home</a>
            </li>
            <li class="breadcrumb-item">
                <a 
                    href="{% url 'revision:qualification' subject.qualification.slug %}"
                    class="link-secondary link-underline-opacity-0 text-info">{{ subject.qualification.name }}</a>
            </li>
            <li class="breadcrumb-item" aria-current="page">{{ subject.name }}</li>
        </ol>
    </nav>
{% endblock breadcrumb %}
{% block page_header %}
    <h1 class="border-none pb-2 my-3 d-flex justify-content-center display-5 fw-bold text-body-emphasis">
        {{ subject.qualification.name }} {{ subject.name }}
    </h1>
    <h5 class="border-none my-0 mb-5 d-flex justify-content-center">Choose your exam board.</h5>
{% endblock page_header %}
{% block content_1 %}
    <div class="row row-cols-1 g-4">
        {% for examboard in examboards %}
            <div class="col-sm-6 mb-3 mb-sm-0">
                <a 
                    class="btn-card shadow-lg card btn btn-primary rounded-3 text-center border border-info pt-2 h-100"
                    href="{% url 'revision:examboard' subject.qualification.slug subject.slug examboard.id examboard.slug %}"> 
                    <div class="card-body">
                        <h5 class="card-title">{{ examboard.name }}</h5>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock content_1 %}

revision/templates/revision/tutoring_contact_sent.html
{% extends 'revision/tutoring_contact.html' %}
{% block content_1 %}
    <div class="container">
        <h2 class="mt-5 py-3 d-flex justify-content-center">
            Sent!
        </h2>
        <h2 class="mt-5 py-3 d-flex justify-content-center">
            We'll get back to you as soon as possible.
        </h2>
    </div>
{% endblock content_1 %}